import { programs } from '@/config/site.config'

// EN/HI copy for the Day 1 / Day 30 assessment (Phase 8, Item 11).
// The reading passages themselves are English only for now.

export const ASSESSMENT_COPY = {
  en: {
    title: 'Day 1 vs Day 30 assessment',
    disclaimer: 'Practice assessment — not a medical or psychological test.',
    about:
      'About 6 minutes: read a short passage at your own normal pace, answer 5 questions, then a 2-minute attention task. Take it on Day 1 and again on Day 30 to see your own progress.',
    startDay1: 'Start Day 1 assessment',
    startDay30: 'Start Day 30 re-test',
    newBaseline: 'Take a new Day 1 baseline',
    newBaselineNote: 'This replaces your current Day 1 result and restarts the 30-day count.',
    pacedOnly:
      'Your Day 1 reading check in the curriculum was app-paced (the app set the speed), so it can’t be compared fairly with a free Day 30 read. Take a new Day 1 baseline now to compare later.',
    noBaseline: 'There is no Day 1 result yet, so no comparison is possible. Take your Day 1 assessment first.',
    locked: (date: string, day: number) => `Your Day 30 re-test opens on ${date} (you are on day ${day} of 30), or as soon as you finish curriculum Day 29.`,
    open: 'Your Day 30 re-test is open.',
    late: 'Late re-test: it is now past day 35, so the gap is longer than 30 days. You can still take it.',
    day1Results: 'Your Day 1 results',
    chooseLanguage: 'Reading language',
    languageNote: 'Choose the language you read best in. Your Day 30 re-test will be in the same language, with a different passage.',
    day30Language: (language: string) => `Your Day 30 passage is in ${language}, the same language as your Day 1.`,
    // Flow
    readIntro: 'Read the passage at your normal pace — not faster than usual. The timer starts when you tap Start and stops when you tap Done. You can’t go back to the text after that.',
    startReading: 'Start reading',
    done: 'Done',
    question: (n: number, total: number) => `Question ${n} of ${total}`,
    next: 'Next',
    attentionTitle: 'Attention task (2 minutes)',
    attentionIntro:
      'Shapes appear one at a time. Tap the button (or press Space) as fast as you can when you see a blue circle ●. Do NOT tap for an orange cross ✕. First, 6 practice shapes.',
    startPractice: 'Start practice',
    practiceDone: 'Practice done. Ready for the real task? It takes about 2 minutes.',
    startTask: 'Start the task',
    tap: 'Tap',
    saving: 'Saving your results…',
    errorImplausible: 'The reading time looks wrong (too fast or too slow for the passage). Please try again and read at your normal pace.',
    errorGeneric: 'Could not save your results. Please try again.',
    retry: 'Try again',
    // Results
    resultsTitle: 'Your Day 1 → Day 30 results',
    metrics: {
      wpm: 'Reading speed (words per minute)',
      comprehension: 'Comprehension',
      effective: 'Effective reading speed',
      accuracy: 'Attention accuracy',
      rt: 'Average reaction time',
    },
    effectiveNote: 'Effective reading speed = words per minute × comprehension %. Reading faster only counts when you still understand.',
    rtNote: 'For reaction time, lower is faster.',
    changeUp: (pct: number) => `+${pct}%`,
    changeDown: (pct: number) => `−${pct}%`,
    noChange: 'no change',
    day1: 'Day 1',
    day30: 'Day 30',
    share: 'Create a share card',
    shareNote: 'The card is made on your device and shows your first name and these numbers only. Nothing is shared unless you choose to.',
    download: 'Download image',
    shareButton: 'Share',
    card: {
      program: programs.sharpBrain.name,
      heading: (firstName: string | null) => (firstName === null ? 'Day 1 → Day 30' : `${firstName}’s Day 1 → Day 30`),
      rows: { wpm: 'Reading speed (wpm)', comprehension: 'Comprehension', effective: 'Effective reading speed', accuracy: 'Attention accuracy' },
      disclaimer: 'Practice assessment — not a medical or psychological test',
    },
  },
  hi: {
    title: 'दिन 1 बनाम दिन 30 असेसमेंट',
    disclaimer: 'अभ्यास असेसमेंट — यह कोई मेडिकल या मनोवैज्ञानिक टेस्ट नहीं है।',
    about:
      'लगभग 6 मिनट: अपनी सामान्य गति से एक छोटा पैसेज पढ़ें, 5 सवालों के जवाब दें, फिर 2 मिनट का ध्यान (अटेंशन) टास्क। इसे दिन 1 पर और फिर दिन 30 पर करें, ताकि आप अपनी प्रगति देख सकें।',
    startDay1: 'दिन 1 असेसमेंट शुरू करें',
    startDay30: 'दिन 30 री-टेस्ट शुरू करें',
    newBaseline: 'नया दिन 1 बेसलाइन लें',
    newBaselineNote: 'यह आपका मौजूदा दिन 1 परिणाम बदल देगा और 30 दिनों की गिनती फिर से शुरू होगी।',
    pacedOnly:
      'करिकुलम में आपका दिन 1 रीडिंग चेक ऐप की तय गति पर था, इसलिए उसकी तुलना दिन 30 की अपनी गति वाली रीडिंग से ठीक से नहीं हो सकती। बाद में तुलना के लिए अभी नया दिन 1 बेसलाइन लें।',
    noBaseline: 'अभी कोई दिन 1 परिणाम नहीं है, इसलिए तुलना संभव नहीं है। पहले अपना दिन 1 असेसमेंट करें।',
    locked: (date: string, day: number) => `आपका दिन 30 री-टेस्ट ${date} को खुलेगा (आप 30 में से दिन ${day} पर हैं), या करिकुलम का दिन 29 पूरा करते ही।`,
    open: 'आपका दिन 30 री-टेस्ट खुला है।',
    late: 'देर से री-टेस्ट: दिन 35 बीत चुका है, इसलिए अंतर 30 दिनों से ज़्यादा है। आप फिर भी इसे दे सकते हैं।',
    day1Results: 'आपके दिन 1 के परिणाम',
    chooseLanguage: 'पढ़ने की भाषा',
    languageNote: 'वह भाषा चुनें जिसमें आप सबसे अच्छा पढ़ते हैं। आपका दिन 30 री-टेस्ट इसी भाषा में होगा, एक अलग पैसेज के साथ।',
    day30Language: (language: string) => `आपका दिन 30 पैसेज ${language} में है — वही भाषा जो दिन 1 में थी।`,
    readIntro: 'पैसेज अपनी सामान्य गति से पढ़ें — सामान्य से तेज़ नहीं। Start दबाते ही टाइमर शुरू होगा और Done दबाने पर रुकेगा। उसके बाद आप टेक्स्ट पर वापस नहीं जा सकेंगे।',
    startReading: 'पढ़ना शुरू करें',
    done: 'हो गया',
    question: (n: number, total: number) => `सवाल ${n} / ${total}`,
    next: 'आगे',
    attentionTitle: 'ध्यान टास्क (2 मिनट)',
    attentionIntro:
      'एक-एक करके आकृतियां दिखेंगी। नीला गोला ● दिखते ही जितनी जल्दी हो सके बटन दबाएं (या Space दबाएं)। नारंगी क्रॉस ✕ पर न दबाएं। पहले 6 अभ्यास आकृतियां।',
    startPractice: 'अभ्यास शुरू करें',
    practiceDone: 'अभ्यास पूरा हुआ। असली टास्क के लिए तैयार हैं? इसमें लगभग 2 मिनट लगते हैं।',
    startTask: 'टास्क शुरू करें',
    tap: 'दबाएं',
    saving: 'आपके परिणाम सेव हो रहे हैं…',
    errorImplausible: 'पढ़ने का समय सही नहीं लग रहा (पैसेज के हिसाब से बहुत तेज़ या बहुत धीमा)। कृपया अपनी सामान्य गति से फिर से पढ़ें।',
    errorGeneric: 'परिणाम सेव नहीं हो सके। कृपया फिर से कोशिश करें।',
    retry: 'फिर से कोशिश करें',
    resultsTitle: 'आपके दिन 1 → दिन 30 के परिणाम',
    metrics: {
      wpm: 'रीडिंग स्पीड (शब्द प्रति मिनट)',
      comprehension: 'समझ (कॉम्प्रिहेंशन)',
      effective: 'प्रभावी रीडिंग स्पीड',
      accuracy: 'ध्यान की सटीकता',
      rt: 'औसत प्रतिक्रिया समय',
    },
    effectiveNote: 'प्रभावी रीडिंग स्पीड = शब्द प्रति मिनट × समझ %। तेज़ पढ़ना तभी गिना जाता है जब आप समझ भी रहे हों।',
    rtNote: 'प्रतिक्रिया समय में कम का मतलब तेज़ है।',
    changeUp: (pct: number) => `+${pct}%`,
    changeDown: (pct: number) => `−${pct}%`,
    noChange: 'कोई बदलाव नहीं',
    day1: 'दिन 1',
    day30: 'दिन 30',
    share: 'शेयर कार्ड बनाएं',
    shareNote: 'कार्ड आपके डिवाइस पर बनता है और इसमें सिर्फ़ आपका पहला नाम और ये आंकड़े होते हैं। आप चुनें तभी कुछ शेयर होगा।',
    download: 'इमेज डाउनलोड करें',
    shareButton: 'शेयर करें',
    card: {
      program: programs.sharpBrain.nameHi,
      heading: (firstName: string | null) => (firstName === null ? 'दिन 1 → दिन 30' : `${firstName} — दिन 1 → दिन 30`),
      rows: { wpm: 'रीडिंग स्पीड (शब्द/मिनट)', comprehension: 'समझ', effective: 'प्रभावी रीडिंग स्पीड', accuracy: 'ध्यान की सटीकता' },
      disclaimer: 'अभ्यास असेसमेंट — मेडिकल या मनोवैज्ञानिक टेस्ट नहीं',
    },
  },
} as const

export type AssessmentCopy = (typeof ASSESSMENT_COPY)['en'] | (typeof ASSESSMENT_COPY)['hi']
