// Regenerates src/lib/app-i18n/catalog.ts from the folders in
// src/lib/app-i18n/messages/<lang>/<namespace>.json. Run after adding a
// namespace:  node scripts/i18n-catalog.mjs
import fs from 'node:fs'
import path from 'node:path'

const ROOT = 'src/lib/app-i18n/messages'
const LANGS = ['en', 'hi', 'kn', 'ta', 'te', 'mr', 'gu']
const namespaces = fs.readdirSync(path.join(ROOT, 'en')).filter((f) => f.endsWith('.json')).map((f) => f.replace(/\.json$/, '')).sort()

for (const lang of LANGS) {
  fs.mkdirSync(path.join(ROOT, lang), { recursive: true })
  for (const ns of namespaces) {
    const file = path.join(ROOT, lang, `${ns}.json`)
    if (!fs.existsSync(file)) fs.writeFileSync(file, '{}\n')
  }
}

const id = (lang, ns) => `${lang}_${ns.replace(/[^a-zA-Z0-9]/g, '_')}`
let out = `// GENERATED by scripts/i18n-catalog.mjs — do not edit by hand.\n// Server-side catalog of every app language. Client components get only\n// the active language (already merged over English) from AppI18nProvider.\n\nimport type { AppLang } from './languages'\nimport type { MessageDict } from './translate'\n\n`
for (const lang of LANGS) for (const ns of namespaces) out += `import ${id(lang, ns)} from './messages/${lang}/${ns}.json'\n`
out += `\nexport const NAMESPACES = ${JSON.stringify(namespaces)} as const\n\n`
out += `// eslint-disable-next-line @typescript-eslint/no-unused-vars -- only its type is used\nconst english = {\n${namespaces.map((ns) => `  ${JSON.stringify(ns)}: ${id('en', ns)},`).join('\n')}\n}\n\nexport type EnglishMessages = typeof english\n\n`
out += `export const CATALOG: Record<AppLang, MessageDict> = {\n`
for (const lang of LANGS) out += `  ${lang}: {\n${namespaces.map((ns) => `    ${JSON.stringify(ns)}: ${id(lang, ns)} as MessageDict,`).join('\n')}\n  },\n`
out += `}\n\nexport const ENGLISH: MessageDict = CATALOG.en\n`
fs.writeFileSync('src/lib/app-i18n/catalog.ts', out)

// English only, for client components rendered outside AppI18nProvider
// (shared pieces that also appear on website pages).
let en = `// GENERATED by scripts/i18n-catalog.mjs — do not edit by hand.\n// English messages only — the client fallback outside AppI18nProvider.\n\nimport type { MessageDict } from './translate'\n\n`
for (const ns of namespaces) en += `import ${id('en', ns)} from './messages/en/${ns}.json'\n`
en += `\nexport const ENGLISH_MESSAGES: MessageDict = {\n${namespaces.map((ns) => `  ${JSON.stringify(ns)}: ${id('en', ns)} as MessageDict,`).join('\n')}\n}\n`
fs.writeFileSync('src/lib/app-i18n/english.ts', en)
console.log(`catalog.ts: ${LANGS.length} languages × ${namespaces.length} namespaces (${namespaces.join(', ')})`)
