'use client'

// Mixed Flash™ Experience — Mission 4, the Flash Intelligence Pack™'s
// Boss Mission. Runs on the exact same Flash Engine every prior mission
// uses: UniversalExercisePlayer, the shared combo/focus/avg-response-time
// displays, and the Mission Complete screen. The only thing genuinely new
// here is the ORCHESTRATION — deciding which stimulus type (word/number/
// symbol) each challenge is — and even that hands off immediately to the
// already-tested per-type builders (buildWordFlashItems,
// buildNumberFlashItems, buildSymbolFlashItems). No distractor logic, no
// speed system, no result-screen mechanics are reimplemented here.

import { useCallback, useMemo, useState } from 'react'
import { UniversalExercisePlayer } from '@/components/exercise-engine/UniversalExercisePlayer'
import type { RuntimeResultExtraStat, RuntimeResultLabels } from '@/components/exercise-engine/RuntimeResultScreen'
import type { RuntimeResult } from '@/hooks/exercise-engine/useUniversalExerciseRuntime'
import { MIXED_FLASH_DEFINITION } from '../definitions/mixedFlashDefinition'
import {
  buildMixedFlashSession,
  computeStimulusBreakdown,
  findWeakestStimulusType,
  findStrongestStimulusType,
  computeRecognitionRatePerMinute,
  type MixedFlashStimulusType,
} from '../mixedFlashEngine'
import { getMixedFlashProfile, mixedFlashUiLevel, mixedFlashPaceDescriptor } from '../mixedFlashDifficulty'
import { computeMixedFlashProgression } from '../mixedFlashProgression'
import { buildMixedFlashRecommendation } from '../mixedFlashRecommendation'
import { appendMixedFlashSession, computeMixedFlashAnalytics, getRecentlyShownByType } from '../mixedFlashHistory'
// Reused, read-only, from Word Flash — pure functions with no mission-
// specific state. Importing them here is genuine reuse, not duplication;
// wordFlashEngine.ts / wordFlashInsights.ts are not modified.
import { computeFlashXp } from '../wordFlashEngine'
import { computeMasteryPercent, computeReadingReadiness } from '../wordFlashInsights'
import { loadState } from '@/lib/exercise-engine/sessionEngine'

// Register all three datasets Mixed Flash draws from. Word Flash's is
// already registered incidentally (mixedFlashDefinition.ts imports
// WORD_FLASH_DATASET directly), but Number Flash's and Symbol Flash's are
// not pulled in by any other Mixed Flash import — without these, a
// player who opens Mixed Flash without having visited Number/Symbol
// Flash first in the same session gets empty pools for those types,
// silently losing every number/symbol challenge. Found via live testing,
// not assumed.
import '../wordFlashDataset'
import '../numberFlashDataset'
import '../symbolFlashDataset'

const EXERCISE_ID = 'mixed-flash'
// Sprint-12: Flash Intelligence Pack™ is now one guided sequence — this
// points at the next real mission (Peripheral Flash), not back to the lab hub.
const NEXT_EXERCISE_HREF = '/labs/sharp-brain/peripheral-flash'

const PLAYER_COPY = {
  exit: 'Exit Mission',
  begin: 'Start Mission',
  paused: 'Mission Paused',
  gap: 'Next Flash',
  ready: 'Mission Ready',
  go: 'FLASH',
  prompt: 'Brain Challenge',
  itemNoun: 'Challenge',
}

const RESULT_LABELS: RuntimeResultLabels = {
  completeSuffix: 'Recognition Switching Strengthened',
  correctLabel: 'Recognition Accuracy',
  speedLabel: 'Flash Speed',
  scoreLabel: 'Mission Score',
  reactionLabel: 'Average Response Time',
  practiceAgainLabel: 'Retry Mission',
  nextLabel: 'Continue to Next Mission',
}

const TYPE_DISPLAY_LABEL: Record<MixedFlashStimulusType, string> = {
  word: 'Words',
  number: 'Numbers',
  symbol: 'Symbols',
}

export function MixedFlashExperience(): React.JSX.Element {
  const [sessionKey, setSessionKey] = useState(0)

  const state = useMemo(
    () => loadState(EXERCISE_ID),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [sessionKey],
  )
  const profile = useMemo(() => getMixedFlashProfile(state.currentDifficultyTier), [state.currentDifficultyTier])

  const analytics = useMemo(
    () => computeMixedFlashAnalytics(EXERCISE_ID),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [sessionKey],
  )

  // Build the session: an unpredictable word/number/symbol sequence at
  // the player's current tier, each item generated by the exact same
  // builder its own mission uses. itemTypes is kept alongside items so
  // the result screen can compute a real per-type breakdown later.
  const { items, itemTypes } = useMemo(() => {
    const seed = Date.now() + sessionKey * 99991
    const recentlyShownByType = getRecentlyShownByType(EXERCISE_ID)
    return buildMixedFlashSession({
      tier: state.currentDifficultyTier,
      itemCount: profile.itemsPerSession,
      seed,
      recentlyShownByType,
    })
  }, [state.currentDifficultyTier, profile.itemsPerSession, sessionKey])

  // Static difficulty indicator — Mixed Flash's tier doesn't ramp within
  // a session (see mixedFlashDifficulty.ts), so this always reads the
  // same current level throughout, which is honest: nothing about the
  // difficulty actually changes challenge to challenge here.
  const computeDifficultyLabel = useCallback((): string => {
    return mixedFlashUiLevel(state.currentDifficultyTier)
  }, [state.currentDifficultyTier])

  const computeExtraStats = useCallback((result: RuntimeResult): RuntimeResultExtraStat[] => {
    const { metrics } = result
    const ratePerMinute = computeRecognitionRatePerMinute(metrics.averageReactionTimeMs)
    const flashXpEarned = computeFlashXp(metrics.performanceScore, metrics.totalCount)
    const blendedAccuracy = analytics.totalSessions > 0
      ? (analytics.averageAccuracy * analytics.totalSessions + metrics.accuracyPercent) / (analytics.totalSessions + 1)
      : metrics.accuracyPercent
    const masteryPercent = computeMasteryPercent(metrics.difficultyTier, blendedAccuracy)

    return [
      {
        label: 'Recognition Speed',
        value: `${ratePerMinute}/min`,
        hint: 'Stimuli recognized per minute at this mission’s pace, across all types.',
      },
      {
        label: 'Brain XP',
        value: `+${flashXpEarned}`,
        hint: 'Personal mastery points from this mission — never compared to other users.',
      },
      {
        label: 'Mastery Progress',
        value: `${masteryPercent}%`,
        hint: 'Blends your current level with your accuracy consistency.',
      },
    ]
  }, [analytics.averageAccuracy, analytics.totalSessions])

  const computeCoachMessage = useCallback((result: RuntimeResult): string => {
    const { metrics, responses } = result
    const breakdown = computeStimulusBreakdown(responses, itemTypes)
    const weakestType = findWeakestStimulusType(breakdown)
    const strongestType = findStrongestStimulusType(breakdown)

    const progression = computeMixedFlashProgression({
      currentTier: metrics.difficultyTier,
      recentAccuracies: [...state.progressCurve.slice(-2), metrics.accuracyPercent],
      averageReactionMs: metrics.averageReactionTimeMs,
      sessionsAtCurrentTier: state.sessionCount,
    })
    const recommendation = buildMixedFlashRecommendation({
      accuracyPercent: metrics.accuracyPercent,
      currentTier: metrics.difficultyTier,
      nextTier: progression.nextTier,
      promoted: progression.promoted,
      recovered: progression.recovered,
      breakdown,
      weakestType,
      strongestType,
    })
    return `${recommendation.coachParagraph} You're training recognition switching — the mental flexibility that keeps your reading pace steady even as content changes.`
  }, [state.progressCurve, state.sessionCount, itemTypes])

  // Stimulus Breakdown + Estimated Reading Readiness — the redesigned
  // Mission Complete screen's secondary summary, matching Word Flash's
  // extraContent styling exactly (reused visual pattern, not reused code
  // — RuntimeResultScreen's extraContent slot is a generic ReactNode, so
  // each mission supplies its own markup through the same mechanism).
  const computeResultExtraContent = useCallback((result: RuntimeResult): React.ReactNode => {
    const { metrics, responses } = result
    const breakdown = computeStimulusBreakdown(responses, itemTypes)
    const readiness = computeReadingReadiness(metrics.accuracyPercent, profile.requiredAccuracyToAdvance)

    const typeOrder: MixedFlashStimulusType[] = ['word', 'number', 'symbol']
    const breakdownLine = typeOrder
      .filter((type) => breakdown[type].total > 0)
      .map((type) => {
        const { correct, total } = breakdown[type]
        const pct = total > 0 ? Math.round((correct / total) * 100) : 0
        return `${TYPE_DISPLAY_LABEL[type]} ${correct}/${total} (${pct}%)`
      })
      .join(' · ')

    return (
      <div className="space-y-1 text-xs text-muted-foreground">
        <p>Stimulus Breakdown: <span className="font-medium text-foreground">{breakdownLine || 'Still gathering data'}</span></p>
        <p>Estimated Reading Readiness: <span className="font-medium text-foreground">{readiness}</span></p>
      </div>
    )
  }, [profile.requiredAccuracyToAdvance, itemTypes])

  const handleResultReady = useCallback((result: RuntimeResult): void => {
    const { metrics, longestComboThisSession } = result
    const ratePerMinute = computeRecognitionRatePerMinute(metrics.averageReactionTimeMs)

    const progression = computeMixedFlashProgression({
      currentTier: metrics.difficultyTier,
      recentAccuracies: [...state.progressCurve.slice(-2), metrics.accuracyPercent],
      averageReactionMs: metrics.averageReactionTimeMs,
      sessionsAtCurrentTier: state.sessionCount,
    })

    const stimuliByType: Record<MixedFlashStimulusType, string[]> = { word: [], number: [], symbol: [] }
    for (const item of items) {
      const type = itemTypes.get(item.id)
      if (type !== undefined) stimuliByType[type].push(item.stimulus)
    }

    appendMixedFlashSession(EXERCISE_ID, {
      timestamp: Date.now(),
      tier: metrics.difficultyTier,
      accuracyPercent: metrics.accuracyPercent,
      flashDurationMs: metrics.speedMs,
      itemCount: metrics.totalCount,
      promoted: progression.promoted,
      recovered: progression.recovered,
      recognitionRatePerMinute: ratePerMinute,
      longestComboThisSession,
      stimuliByType,
    })
  }, [state.progressCurve, state.sessionCount, items, itemTypes])

  function handleRestart(): void {
    setSessionKey((k) => k + 1)
  }

  return (
    <UniversalExercisePlayer
      key={sessionKey}
      definition={{
        ...MIXED_FLASH_DEFINITION,
        metaLine: `${mixedFlashUiLevel(state.currentDifficultyTier)} · ${mixedFlashPaceDescriptor(state.currentDifficultyTier)} pace · ${profile.itemsPerSession} challenges per mission — word, number, or symbol, never announced${analytics.totalSessions > 0 ? ` · Mission ${analytics.totalSessions + 1}` : ''}`,
      }}
      items={items}
      onRestart={handleRestart}
      onResultReady={handleResultReady}
      computeExtraStats={computeExtraStats}
      computeCoachMessage={computeCoachMessage}
      computeResultExtraContent={computeResultExtraContent}
      resultLabels={RESULT_LABELS}
      copy={PLAYER_COPY}
      showCombo
      showFocusLevel
      showAverageResponseTime
      computeDifficultyLabel={computeDifficultyLabel}
      nextExerciseHref={NEXT_EXERCISE_HREF}
    />
  )
}
