// GENERATED by scripts/i18n-catalog.mjs — do not edit by hand.
// Server-side catalog of every app language. Client components get only
// the active language (already merged over English) from AppI18nProvider.

import type { AppLang } from './languages'
import type { MessageDict } from './translate'

import en_auth from './messages/en/auth.json'
import en_common from './messages/en/common.json'
import en_curriculum from './messages/en/curriculum.json'
import en_curriculumPlan from './messages/en/curriculumPlan.json'
import en_dashboard from './messages/en/dashboard.json'
import en_docWidget from './messages/en/docWidget.json'
import en_enrol from './messages/en/enrol.json'
import en_exercises from './messages/en/exercises.json'
import en_mentor from './messages/en/mentor.json'
import en_nav from './messages/en/nav.json'
import en_progress from './messages/en/progress.json'
import en_settings from './messages/en/settings.json'
import en_welcome from './messages/en/welcome.json'
import hi_auth from './messages/hi/auth.json'
import hi_common from './messages/hi/common.json'
import hi_curriculum from './messages/hi/curriculum.json'
import hi_curriculumPlan from './messages/hi/curriculumPlan.json'
import hi_dashboard from './messages/hi/dashboard.json'
import hi_docWidget from './messages/hi/docWidget.json'
import hi_enrol from './messages/hi/enrol.json'
import hi_exercises from './messages/hi/exercises.json'
import hi_mentor from './messages/hi/mentor.json'
import hi_nav from './messages/hi/nav.json'
import hi_progress from './messages/hi/progress.json'
import hi_settings from './messages/hi/settings.json'
import hi_welcome from './messages/hi/welcome.json'
import kn_auth from './messages/kn/auth.json'
import kn_common from './messages/kn/common.json'
import kn_curriculum from './messages/kn/curriculum.json'
import kn_curriculumPlan from './messages/kn/curriculumPlan.json'
import kn_dashboard from './messages/kn/dashboard.json'
import kn_docWidget from './messages/kn/docWidget.json'
import kn_enrol from './messages/kn/enrol.json'
import kn_exercises from './messages/kn/exercises.json'
import kn_mentor from './messages/kn/mentor.json'
import kn_nav from './messages/kn/nav.json'
import kn_progress from './messages/kn/progress.json'
import kn_settings from './messages/kn/settings.json'
import kn_welcome from './messages/kn/welcome.json'
import ta_auth from './messages/ta/auth.json'
import ta_common from './messages/ta/common.json'
import ta_curriculum from './messages/ta/curriculum.json'
import ta_curriculumPlan from './messages/ta/curriculumPlan.json'
import ta_dashboard from './messages/ta/dashboard.json'
import ta_docWidget from './messages/ta/docWidget.json'
import ta_enrol from './messages/ta/enrol.json'
import ta_exercises from './messages/ta/exercises.json'
import ta_mentor from './messages/ta/mentor.json'
import ta_nav from './messages/ta/nav.json'
import ta_progress from './messages/ta/progress.json'
import ta_settings from './messages/ta/settings.json'
import ta_welcome from './messages/ta/welcome.json'
import te_auth from './messages/te/auth.json'
import te_common from './messages/te/common.json'
import te_curriculum from './messages/te/curriculum.json'
import te_curriculumPlan from './messages/te/curriculumPlan.json'
import te_dashboard from './messages/te/dashboard.json'
import te_docWidget from './messages/te/docWidget.json'
import te_enrol from './messages/te/enrol.json'
import te_exercises from './messages/te/exercises.json'
import te_mentor from './messages/te/mentor.json'
import te_nav from './messages/te/nav.json'
import te_progress from './messages/te/progress.json'
import te_settings from './messages/te/settings.json'
import te_welcome from './messages/te/welcome.json'
import mr_auth from './messages/mr/auth.json'
import mr_common from './messages/mr/common.json'
import mr_curriculum from './messages/mr/curriculum.json'
import mr_curriculumPlan from './messages/mr/curriculumPlan.json'
import mr_dashboard from './messages/mr/dashboard.json'
import mr_docWidget from './messages/mr/docWidget.json'
import mr_enrol from './messages/mr/enrol.json'
import mr_exercises from './messages/mr/exercises.json'
import mr_mentor from './messages/mr/mentor.json'
import mr_nav from './messages/mr/nav.json'
import mr_progress from './messages/mr/progress.json'
import mr_settings from './messages/mr/settings.json'
import mr_welcome from './messages/mr/welcome.json'
import gu_auth from './messages/gu/auth.json'
import gu_common from './messages/gu/common.json'
import gu_curriculum from './messages/gu/curriculum.json'
import gu_curriculumPlan from './messages/gu/curriculumPlan.json'
import gu_dashboard from './messages/gu/dashboard.json'
import gu_docWidget from './messages/gu/docWidget.json'
import gu_enrol from './messages/gu/enrol.json'
import gu_exercises from './messages/gu/exercises.json'
import gu_mentor from './messages/gu/mentor.json'
import gu_nav from './messages/gu/nav.json'
import gu_progress from './messages/gu/progress.json'
import gu_settings from './messages/gu/settings.json'
import gu_welcome from './messages/gu/welcome.json'

export const NAMESPACES = ["auth","common","curriculum","curriculumPlan","dashboard","docWidget","enrol","exercises","mentor","nav","progress","settings","welcome"] as const

// eslint-disable-next-line @typescript-eslint/no-unused-vars -- only its type is used
const english = {
  "auth": en_auth,
  "common": en_common,
  "curriculum": en_curriculum,
  "curriculumPlan": en_curriculumPlan,
  "dashboard": en_dashboard,
  "docWidget": en_docWidget,
  "enrol": en_enrol,
  "exercises": en_exercises,
  "mentor": en_mentor,
  "nav": en_nav,
  "progress": en_progress,
  "settings": en_settings,
  "welcome": en_welcome,
}

export type EnglishMessages = typeof english

export const CATALOG: Record<AppLang, MessageDict> = {
  en: {
    "auth": en_auth as MessageDict,
    "common": en_common as MessageDict,
    "curriculum": en_curriculum as MessageDict,
    "curriculumPlan": en_curriculumPlan as MessageDict,
    "dashboard": en_dashboard as MessageDict,
    "docWidget": en_docWidget as MessageDict,
    "enrol": en_enrol as MessageDict,
    "exercises": en_exercises as MessageDict,
    "mentor": en_mentor as MessageDict,
    "nav": en_nav as MessageDict,
    "progress": en_progress as MessageDict,
    "settings": en_settings as MessageDict,
    "welcome": en_welcome as MessageDict,
  },
  hi: {
    "auth": hi_auth as MessageDict,
    "common": hi_common as MessageDict,
    "curriculum": hi_curriculum as MessageDict,
    "curriculumPlan": hi_curriculumPlan as MessageDict,
    "dashboard": hi_dashboard as MessageDict,
    "docWidget": hi_docWidget as MessageDict,
    "enrol": hi_enrol as MessageDict,
    "exercises": hi_exercises as MessageDict,
    "mentor": hi_mentor as MessageDict,
    "nav": hi_nav as MessageDict,
    "progress": hi_progress as MessageDict,
    "settings": hi_settings as MessageDict,
    "welcome": hi_welcome as MessageDict,
  },
  kn: {
    "auth": kn_auth as MessageDict,
    "common": kn_common as MessageDict,
    "curriculum": kn_curriculum as MessageDict,
    "curriculumPlan": kn_curriculumPlan as MessageDict,
    "dashboard": kn_dashboard as MessageDict,
    "docWidget": kn_docWidget as MessageDict,
    "enrol": kn_enrol as MessageDict,
    "exercises": kn_exercises as MessageDict,
    "mentor": kn_mentor as MessageDict,
    "nav": kn_nav as MessageDict,
    "progress": kn_progress as MessageDict,
    "settings": kn_settings as MessageDict,
    "welcome": kn_welcome as MessageDict,
  },
  ta: {
    "auth": ta_auth as MessageDict,
    "common": ta_common as MessageDict,
    "curriculum": ta_curriculum as MessageDict,
    "curriculumPlan": ta_curriculumPlan as MessageDict,
    "dashboard": ta_dashboard as MessageDict,
    "docWidget": ta_docWidget as MessageDict,
    "enrol": ta_enrol as MessageDict,
    "exercises": ta_exercises as MessageDict,
    "mentor": ta_mentor as MessageDict,
    "nav": ta_nav as MessageDict,
    "progress": ta_progress as MessageDict,
    "settings": ta_settings as MessageDict,
    "welcome": ta_welcome as MessageDict,
  },
  te: {
    "auth": te_auth as MessageDict,
    "common": te_common as MessageDict,
    "curriculum": te_curriculum as MessageDict,
    "curriculumPlan": te_curriculumPlan as MessageDict,
    "dashboard": te_dashboard as MessageDict,
    "docWidget": te_docWidget as MessageDict,
    "enrol": te_enrol as MessageDict,
    "exercises": te_exercises as MessageDict,
    "mentor": te_mentor as MessageDict,
    "nav": te_nav as MessageDict,
    "progress": te_progress as MessageDict,
    "settings": te_settings as MessageDict,
    "welcome": te_welcome as MessageDict,
  },
  mr: {
    "auth": mr_auth as MessageDict,
    "common": mr_common as MessageDict,
    "curriculum": mr_curriculum as MessageDict,
    "curriculumPlan": mr_curriculumPlan as MessageDict,
    "dashboard": mr_dashboard as MessageDict,
    "docWidget": mr_docWidget as MessageDict,
    "enrol": mr_enrol as MessageDict,
    "exercises": mr_exercises as MessageDict,
    "mentor": mr_mentor as MessageDict,
    "nav": mr_nav as MessageDict,
    "progress": mr_progress as MessageDict,
    "settings": mr_settings as MessageDict,
    "welcome": mr_welcome as MessageDict,
  },
  gu: {
    "auth": gu_auth as MessageDict,
    "common": gu_common as MessageDict,
    "curriculum": gu_curriculum as MessageDict,
    "curriculumPlan": gu_curriculumPlan as MessageDict,
    "dashboard": gu_dashboard as MessageDict,
    "docWidget": gu_docWidget as MessageDict,
    "enrol": gu_enrol as MessageDict,
    "exercises": gu_exercises as MessageDict,
    "mentor": gu_mentor as MessageDict,
    "nav": gu_nav as MessageDict,
    "progress": gu_progress as MessageDict,
    "settings": gu_settings as MessageDict,
    "welcome": gu_welcome as MessageDict,
  },
}

export const ENGLISH: MessageDict = CATALOG.en
