// GENERATED by scripts/i18n-catalog.mjs — do not edit by hand.
// English messages only — the client fallback outside AppI18nProvider.

import type { MessageDict } from './translate'

import en_auth from './messages/en/auth.json'
import en_common from './messages/en/common.json'
import en_curriculum from './messages/en/curriculum.json'
import en_curriculumPlan from './messages/en/curriculumPlan.json'
import en_dashboard from './messages/en/dashboard.json'
import en_docWidget from './messages/en/docWidget.json'
import en_enrol from './messages/en/enrol.json'
import en_exercises from './messages/en/exercises.json'
import en_mentor from './messages/en/mentor.json'
import en_nav from './messages/en/nav.json'
import en_progress from './messages/en/progress.json'
import en_settings from './messages/en/settings.json'
import en_welcome from './messages/en/welcome.json'

export const ENGLISH_MESSAGES: MessageDict = {
  "auth": en_auth as MessageDict,
  "common": en_common as MessageDict,
  "curriculum": en_curriculum as MessageDict,
  "curriculumPlan": en_curriculumPlan as MessageDict,
  "dashboard": en_dashboard as MessageDict,
  "docWidget": en_docWidget as MessageDict,
  "enrol": en_enrol as MessageDict,
  "exercises": en_exercises as MessageDict,
  "mentor": en_mentor as MessageDict,
  "nav": en_nav as MessageDict,
  "progress": en_progress as MessageDict,
  "settings": en_settings as MessageDict,
  "welcome": en_welcome as MessageDict,
}
