import type { ExerciseDefinition } from '@/types/exercise-engine'
import { DEFAULT_SCORING_RULES } from '@/types/exercise-engine'
import { CHUNK_READING_DATASET } from '../chunkDataset'

export const CHUNK_READING_DEFINITION: ExerciseDefinition = {
  id: 'chunk-reading',
  labId: 'quantum-speed-reading',
  title: 'Chunk Reading™',
  description: 'A meaningful word group flashes briefly — identify it before it disappears. Chunk length increases as your visual span expands.',
  trainsAbility: 'Multi-word visual span',
  exerciseType: 'flash',
  contentType: 'chunk',
  interactionType: 'multiple-choice',
  dataset: CHUNK_READING_DATASET,
  adaptiveRules: {
    increaseSpeedAbove: 88,
    decreaseSpeedBelow: 65,
    minSpeedMs: 200,
    maxSpeedMs: 1000,
    defaultSpeedMs: 700,
    itemsPerSession: 20,
    minAccuracyToComplete: 60,
  },
  speedMode: 'adaptive',
  scoringRules: DEFAULT_SCORING_RULES,
  intelligenceDimension: 'reading',
  href: '/labs/sharp-brain/chunk-reading',
  labHref: '/labs/sharp-brain',
  locale: 'en',
  i18nKeys: {
    title: 'exercise.chunk_reading.title',
    description: 'exercise.chunk_reading.description',
    instruction: 'exercise.chunk_reading.instruction',
    startLabel: 'exercise.common.start',
    pauseLabel: 'exercise.common.pause',
    resumeLabel: 'exercise.common.resume',
    exitLabel: 'exercise.common.exit',
    correctLabel: 'exercise.common.correct',
    incorrectLabel: 'exercise.common.incorrect',
    completedLabel: 'exercise.chunk_reading.completed',
    practiceAgainLabel: 'exercise.common.practiceAgain',
    questionPrompt: 'exercise.chunk_reading.questionPrompt',
    keyboardHint: 'exercise.common.keyboardHint',
  },
  config: {},
}
